package bg.tu_varna.sit.api.inputoutput.healthinsurance.updateapply;

import bg.tu_varna.sit.api.contract.OperationProcessor;

public interface HealthInsuranceApplyFormUpdateStatusOperation extends OperationProcessor<HealthInsuranceApplyFormUpdateStatusRequest,HealthInsuranceApplyFormUpdateStatusResponse> {
}
